# Generated by Django 5.0.1 on 2025-10-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blackboxnode_sharedknowledge_zkproof_p2pconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='zkp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zkp_secret_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
