# Generated by Django 5.0.1 on 2025-10-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_zkp_enabled_userprofile_zkp_secret_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='solana_wallet',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wallet_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wallet_verified',
            field=models.BooleanField(default=False),
        ),
    ]
