# Generated by Django 5.0.1 on 2025-10-27 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_userprofile_token_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Parent/Admin'), ('member', 'Family Member'), ('child', 'Child (Restricted)')], default='member', max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('avatar_color', models.CharField(default='#FF6B35', max_length=7)),
                ('storage_quota_gb', models.IntegerField(default=50)),
                ('ai_chat_enabled', models.BooleanField(default=True)),
                ('file_upload_enabled', models.BooleanField(default=True)),
                ('can_share_files', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='vault_files/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=20)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('encryption_key_hash', models.CharField(blank=True, max_length=64)),
                ('ai_description', models.TextField(blank=True)),
                ('ai_tags', models.JSONField(blank=True, default=list)),
                ('ai_processed', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='vault_thumbnails/')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('is_public_to_family', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('download_count', models.IntegerField(default=0)),
                ('blockchain_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.familymember')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_files', to='core.familymember')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FileShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('allow_download', models.BooleanField(default=True)),
                ('allow_preview', models.BooleanField(default=True)),
                ('max_downloads', models.IntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.familymember')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='core.vaultfile')),
            ],
        ),
        migrations.CreateModel(
            name='VaultFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_public_to_family', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='core.familymember')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='core.vaultfolder')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_folders', to='core.familymember')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'owner', 'parent_folder')},
            },
        ),
        migrations.AddField(
            model_name='vaultfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.vaultfolder'),
        ),
        migrations.CreateModel(
            name='VaultActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Uploaded'), ('download', 'Downloaded'), ('delete', 'Deleted'), ('share', 'Shared'), ('view', 'Viewed')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.familymember')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vaultfile')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vaultfolder')),
            ],
            options={
                'verbose_name_plural': 'Vault activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='vaultfile',
            index=models.Index(fields=['owner', 'file_type'], name='core_vaultf_owner_i_d741d2_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultfile',
            index=models.Index(fields=['owner', 'uploaded_at'], name='core_vaultf_owner_i_cdae17_idx'),
        ),
    ]
