# Generated by Django 5.0.1 on 2025-10-29 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_familymember_vaultfile_filesharelink_vaultfolder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGuardianScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('severity', models.CharField(choices=[('safe', 'Safe'), ('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical')], default='safe', max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('detected_patterns', models.JSONField(default=list)),
                ('detected_keywords', models.JSONField(default=list)),
                ('risk_categories', models.JSONField(default=list)),
                ('ai_summary', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('parent_notified', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_scan', to='core.vaultfile')),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.familymember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIGuardianAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('personal_data', 'Personal Data Detected'), ('inappropriate', 'Inappropriate Content'), ('privacy', 'Privacy Concern'), ('security', 'Security Risk'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('reviewing', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('action_taken', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_alerts', to='core.familymember')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to='core.familymember')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.aiguardianscan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
