# Generated by Django 5.0.1 on 2025-10-29 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aiguardianscan_aiguardianalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('encrypted_content', models.TextField(blank=True)),
                ('mood', models.CharField(choices=[('amazing', '😄 Amazing'), ('happy', '😊 Happy'), ('okay', '😐 Okay'), ('sad', '😢 Sad'), ('stressed', '😰 Stressed')], default='okay', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_private', models.BooleanField(default=False)),
                ('entry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_processed', models.BooleanField(default=False)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='core.familymember')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_journal_entries', to='core.familymember')),
            ],
            options={
                'verbose_name_plural': 'Family journal entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMemoryMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('milestone_type', models.CharField(choices=[('achievement', '🏆 Achievement'), ('birthday', '🎂 Birthday'), ('trip', '✈️ Trip/Vacation'), ('special', '⭐ Special Moment'), ('first', '🎉 First Time'), ('other', '💫 Other')], default='special', max_length=20)),
                ('milestone_date', models.DateField()),
                ('photos', models.JSONField(blank=True, default=list)),
                ('auto_detected', models.BooleanField(default=False)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family_members', models.ManyToManyField(related_name='milestones', to='core.familymember')),
                ('journal_entries', models.ManyToManyField(blank=True, related_name='milestones', to='core.familyjournalentry')),
            ],
            options={
                'ordering': ['-milestone_date'],
            },
        ),
        migrations.CreateModel(
            name='FamilyWeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('year', models.IntegerField()),
                ('week_number', models.IntegerField()),
                ('ai_summary', models.TextField()),
                ('highlights', models.JSONField(default=list)),
                ('overall_mood', models.CharField(default='happy', max_length=20)),
                ('total_entries', models.IntegerField(default=0)),
                ('participating_members', models.JSONField(default=list)),
                ('encrypted_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entries', models.ManyToManyField(blank=True, related_name='weekly_summaries', to='core.familyjournalentry')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.familymember')),
            ],
            options={
                'verbose_name_plural': 'Family weekly summaries',
                'ordering': ['-week_start'],
            },
        ),
        migrations.AddIndex(
            model_name='familyjournalentry',
            index=models.Index(fields=['author', 'entry_date'], name='core_family_author__9bd4a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='familyweeklysummary',
            unique_together={('year', 'week_number')},
        ),
    ]
